import { confirm, type ConfirmOr } from "./confirm";

/*
 * Single source of truth for site data (master prompt Part 3).
 * Every place that shows one of these values reads it from this file only.
 * CONFIRM values are client-pending facts; they are never invented.
 */

export const site = {
  name: "EVE Women and Fertility Clinic",
  shortName: "EVE",
  doctor: "Dr. Swati Shree",
  doctorShort: "Dr. Swati",
  phones: [
    { display: "72049 21212", e164: "+917204921212" },
    { display: "72049 21516", e164: "+917204921516" },
  ],
  address: {
    line1: "1st Floor, LG Complex Towers",
    line2: "Gunjur",
    city: "Bangalore",
    region: "Karnataka",
    postalCode: "560087",
    country: "IN",
  },
  foundingYear: 2024,
  foundingMonth: "December",
  hours: confirm("OPD hours"),
  whatsapp: confirm("WhatsApp number"),
  email: confirm("clinic email"),
  mapsUrl: confirm("Google Maps link"),
  geo: confirm("coordinates"),
  registration: {
    kmc: confirm("Karnataka Medical Council number string to display"),
    art: confirm("National ART and Surrogacy Registry number"),
  },
  replyTime: "24 hours",
  legalLastUpdated: confirm("legal pages last-updated date"),
  paymentAccepted: confirm("payment methods accepted"),
  languages: confirm("languages spoken besides English"),
  instagram: confirm("Instagram URL"),
  facebook: confirm("Facebook URL"),
  youtube: confirm("YouTube URL"),
  linkedin: confirm("LinkedIn URL"),
} satisfies Record<string, unknown> & {
  hours: ConfirmOr<string>;
  whatsapp: ConfirmOr<string>;
  email: ConfirmOr<string>;
  mapsUrl: ConfirmOr<string>;
  geo: ConfirmOr<{ lat: number; lng: number }>;
  registration: { kmc: ConfirmOr<string>; art: ConfirmOr<string> };
  legalLastUpdated: ConfirmOr<string>;
  paymentAccepted: ConfirmOr<string>;
  languages: ConfirmOr<string>;
  instagram: ConfirmOr<string>;
  facebook: ConfirmOr<string>;
  youtube: ConfirmOr<string>;
  linkedin: ConfirmOr<string>;
};

/*
 * Absolute base for canonicals and JSON-LD @ids. SITE_URL is set on the
 * production deployment; previews fall back to localhost. The production
 * domain itself is still an open client input (eve-client-data blockers).
 */
export const siteUrl = (process.env.SITE_URL ?? "http://localhost:3000").replace(/\/+$/, "");
export const abs = (path = "/") => `${siteUrl}${path}`;

/** Per-route OG card generated by scripts/og-images.mjs into public/og/. */
export const ogImage = (url: string) =>
  `/og/${url === "/" ? "home" : url.replace(/^\//, "").replace(/\/$/, "").replace(/\//g, "-")}.png`;

export const entityStatement =
  "EVE Women and Fertility Clinic is an outpatient fertility and women's health clinic at LG Complex Towers, Gunjur, Bengaluru (Bangalore), Karnataka 560087, founded in December 2024 by Dr. Swati Shree, MBBS, DNB (Obstetrics and Gynaecology), MRCOG (UK), a reproductive medicine specialist with a fellowship in reproductive medicine. The clinic offers fertility evaluation, natural conception support, follicular monitoring, tubal patency testing, male fertility evaluation, IUI, IVF with lab procedures carried out at associated ART centres, egg freezing and TESA/PESA, along with gynaecological care for PCOS, endometriosis, menstrual disorders, recurrent pregnancy loss, fibroids, adenomyosis, thyroid problems that affect fertility, menopause, early pregnancy scans, cervical screening and HPV vaccination. Patients come from Gunjur, Varthur, Whitefield, Sarjapur Road, Bellandur and other parts of East Bengaluru, and from other cities in India.";

export const brand = {
  logoFull: "brand/logo-full-transparent.png",
  logoWhite: "brand/logo-white-transparent.png",
  logoMark: "brand/logo-mark-transparent.png",
} as const;
