#!/usr/bin/env node
/*
 * launch-check (Part 9.2): fails while any [CONFIRM] remains anywhere in
 * content, config, JSON-LD sources or image captions. Also regenerates
 * client-inputs-needed.md — the checklist of everything still needed from
 * the clinic before launch.
 *
 * Usage: node scripts/launch-check.mjs [--write-inputs]
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { resolve, join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const writeInputs = process.argv.includes('--write-inputs');
const CONFIRM = /\[CONFIRM(?::([^\]]*))?\]|\[(date)\]|confirm\("([^"]+)"\)/g;

const items = []; // { where, note }
const scan = (file, text, label) => {
  for (const m of text.matchAll(CONFIRM)) {
    items.push({ where: `${label} ${relative(root, file).replace(/\\/g, '/')}`, note: (m[1] ?? m[2] ?? m[3] ?? 'value').trim() });
  }
};

// 1. Content files.
const contentDir = join(root, 'resources/content');
(function walk(d) {
  for (const n of readdirSync(d)) {
    const p = join(d, n);
    if (statSync(p).isDirectory()) walk(p);
    else if (n.endsWith('.md')) scan(p, readFileSync(p, 'utf8'), 'content');
  }
})(contentDir);

// 2. Site config (CONFIRM tokens feed JSON-LD as well).
scan(join(root, 'src/lib/site-config.ts'), readFileSync(join(root, 'src/lib/site-config.ts'), 'utf8'), 'config');

// 3. Image captions / alt text.
const altPath = join(root, 'public/images/alt-text.json');
try {
  scan(altPath, readFileSync(altPath, 'utf8'), 'images');
} catch { /* alt-text.json absent */ }

// Site domain is still an open input (schema absolute urls).
items.push({ where: 'config src/lib/site-config.ts', note: 'production domain (SITE_URL)' });
items.push({ where: 'config src/lib/site-config.ts', note: 'opening hours (drives OpeningHoursSpecification)' });

// Write client-inputs-needed.md.
const lines = [
  '# Client inputs needed before launch',
  '',
  `Generated by \`npm run launch-check\` — ${items.length} open item(s).`,
  'Every one of these must be confirmed in writing by the client before indexing is enabled.',
  '',
  '| Where | Needed |',
  '|---|---|',
  ...items.map((i) => `| ${i.where} | ${i.note} |`),
  '',
];
const inputsPath = join(root, 'client-inputs-needed.md');
const body = lines.join('\n');
if (writeInputs || readFileSyncSafe(inputsPath) !== body) writeFileSync(inputsPath, body);
function readFileSyncSafe(p) {
  try { return readFileSync(p, 'utf8'); } catch { return null; }
}

if (items.length) {
  console.log(`launch-check: ${items.length} open [CONFIRM] item(s) — launch blocked.`);
  console.log(`Full list written to client-inputs-needed.md`);
  process.exit(1);
}
console.log('launch-check: no open confirmations. Ready to launch.');
